### PR TITLE
Rename Dockerfile to avoid the ResinCI/docker/build ci job

### PR DESCRIPTION
**Pull request by zvin**
Change-type: patch
Signed-off-by: Alexis Svinartchouk <alexis@resin.io>

### CODE REVIEW

**Comment by zvin** [comment]
@brownjohnf @nazrhom the `ResinCI/npm/store-npm ` job fails with:
```
+ resinci-deploy store npm . -s f943763d694029e08514132a695f4cfcddf96445 -b rename-dockerfile -v 7.0.6
/tmp/build/66d12d10/resinci-deploy/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:26
        throw new Error('Token authentication requires a token to be set')
	^
	

Error: Token authentication requires a token to be set
    at authenticate (/tmp/build/66d12d10/resinci-deploy/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:26:15)
    at Object.<anonymous> (/tmp/build/66d12d10/resinci-deploy/lib/utils.js:7:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/build/66d12d10/resinci-deploy/lib/github.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

**Comment by zvin** [comment]
@resin-ci retest

**Comment by wrboyce** [comment]
Can you try making a `.resinci.yml` file that looks like this:

```yml
---
docker:
  builds: []
```

**Comment by nazrhom** [comment]
@wrboyce that should work. The project should still pass the is-docker check (https://github.com/resin-io/resin-concourse/blob/master/pipelines/github-events/template.yml#L620-L627) but its docker build will be a no-op because builds is empty (https://github.com/resin-io/resin-concourse/blob/master/partials/docker/build.sh#L57-L73)

**Comment by zvin** [comment]
@nazrhom @wrboyce it still tries to build with this `.resinci.yml` file:
```
---
docker:
  builds: []
```

**Pull request merged**
