### PR TITLE
Fix the logic that defines where we get R_OK and W_OK constants for n…

### PR DESCRIPTION
**Pull request by pcarranzav**
…ode 4 support

The _.isUndefined causes the logic to be inverted, so we need to use fs.R_OK if the condition is true.

Change-Type: patch
Signed-off-by: Pablo Carranza Velez <pablo@resin.io>

### CODE REVIEW

**Comment by zvin** [comment]
Sorry about that @pcarranzav

**Comment by pcarranzav** [comment]
no worries @zvin - I've actually done a few similar ones recently :)
would you ping me when it's published on npm?

**Comment by zvin** [comment]
@pcarranzav it's published now: https://www.npmjs.com/package/resin-preload

**Comment by pcarranzav** [comment]
Awesome, thanks!

**Pull request merged**
